---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Пользователь.
--- DateTime: 08.11.2019 19:57
---


local dump = {}

function dump.dump()
    local colorsIndex = { "A", "B", "C", "D", "E", "F" }
    local result = "\t"
    for i = 1, _G.N + 2 do
        if (i > 2) then
            result = result .. (i - 2) .. "|\t"
        end
        if (i == 2) then
            result = result .. "\t"
        end
        for j = 1, _G.M do
            if (i == 1) then
                result = result .. j .. "\t"
            else
                if (i == 2) then
                    result = result .. "_" .. "\t"
                else
                    result = result .. colorsIndex[_G.field[i - 2][j]] .. "\t"
                end
            end
        end
        result = result .. "\n"
    end
    print(result)
end

return dump