---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Пользователь.
--- DateTime: 08.11.2019 10:40
---

local init = {}
local size = 6
local colors = { ["A"] = 1, ["B"] = 2, ["C"] = 3, ["D"] = 4, ["E"] = 5, ["F"] = 6 }
function init.init()
    for i = 1, _G.N do
        for j = 1, _G.M do
            local colorsIndex = { "A", "B", "C", "D", "E", "F" }
            size = 6
            local second = false
            if (i % (_G.K - 1) == 0) then
                table.remove(colorsIndex, _G.field[i - 1][j])
                size = size - 1
                second = true
            end
            if (j % (_G.K - 1) == 0) then
                if (second and _G.field[i - 1][j] < _G.field[i][j - 1]) then
                    local pos = _G.field[i][j - 1] - 1
                else
                    pos = _G.field[i][j - 1]
                end
                table.remove(colorsIndex, pos)
                size = size - 1
            end
            _G.field[i][j] = colors[colorsIndex[math.random(1, size)]]
        end
    end
end

return init