---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Пользователь.
--- DateTime: 07.11.2019 17:05
---

local function main()
    print("put size of field N*M like N M : ")
    _G.N = tonumber(io.read())
    _G.M = tonumber(io.read())
    print("put count of crystal , which can be deleted in line : ")
    _G.K = tonumber(io.read())
    _G.field = { {} }
    _G.currentPosition = { ["X"] = 1, ["Y"] = 1, ["direction"] = "" }
    for i = 1, _G.N do
        _G.field[i] = {}
    end
    require("init").init()
    require("dump").dump()
    local input = ""
    while (true) do
        local indexNegativ = 1
        input = io.read()
        if (input == "q") then
            break
        else
            if (input == "mix") then
                require("mix").mix()
                require("dump").dump()
            else
                local inputArray = {}
                for str in string.gmatch(input, "%w+") do
                    table.insert(inputArray, str)
                end
                require("move").move(tonumber(inputArray[2]), tonumber(inputArray[3]), inputArray[4])
                while (true) do
                    if (require("tick").tick()) then
                        require("dump").dump()
                        indexNegativ = indexNegativ + 1
                    end
                    if (indexNegativ == 1) then
                        require("move").move(_G.currentPosition["X"], _G.currentPosition["Y"], _G.currentPosition["direction"])
                        require("dump").dump()
                        break
                    else
                        break
                    end
                end
            end
        end
    end
end

main()




