---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Пользователь.
--- DateTime: 09.11.2019 5:06
---

local mix = {}

function mix.mix()
    for i = 1, _G.N - 1 do
        for j = 1, _G.M - 1 do
            local temp
            if (i % (_G.K - 1) == 0 and _G.field[i + 1][j] ~= _G.field[i][j] and _G.field[i + 1][j] ~= _G.field[i - 1][j + 1]) then
                temp = _G.field[i - 1][j]
                _G.field[i - 1][j] = _G.field[i + 1][j]
                _G.field[i + 1][j] = temp
            end
        end

    end
end

return mix
