---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Пользователь.
--- DateTime: 09.11.2019 0:16
---

local move = {}

function move.move(x, y, direction)
    if (direction == "l") then
        temp = _G.field[x][y - 1]
        _G.field[x][y - 1] = _G.field[x][y]
        _G.field[x][y] = temp
        _G.currentPosition["X"] = x
        _G.currentPosition["Y"] = y - 1
        _G.currentPosition["direction"] = "r"
    elseif (direction == "r") then
        temp = _G.field[x][y + 1]
        _G.field[x][y + 1] = _G.field[x][y]
        _G.field[x][y] = temp
        _G.currentPosition["X"] = x
        _G.currentPosition["Y"] = y + 1
        _G.currentPosition["direction"] = "l"
    elseif (direction == "u") then
        temp = _G.field[x - 1][y]
        _G.field[x - 1][y] = _G.field[x][y]
        _G.field[x][y] = temp
        _G.currentPosition["X"] = x - 1
        _G.currentPosition["Y"] = y
        _G.currentPosition["direction"] = "d"
    else
        temp = _G.field[x + 1][y]
        _G.field[x + 1][y] = _G.field[x][y]
        _G.field[x][y] = temp
        _G.currentPosition["X"] = x + 1
        _G.currentPosition["Y"] = y
        _G.currentPosition["direction"] = "u"
    end
end

return move