---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Пользователь.
--- DateTime: 11.11.2019 2:21
---

local tick = {}

function tick.tick()
    local deleted = false
    local beginOne
    local beginTwo
    local dirColumn
    local endString
    local beginString
    local column
    for i = 1, _G.N + _G.M do
        local prev
        local count = 0
        if (i > _G.N) then
            endString = _G.N
            beginString = i - _G.N
            column = true
        else
            endString = _G.M
            beginString = i
            column = false
        end
        local index = 0
        for j = 1, endString do
            if (column) then
                index = _G.field[j][beginString]
            else
                index = _G.field[beginString][j]
            end
            if (prev == nil) then
                prev = index
            end
            if (prev == index) then
                count = count + 1
            else
                prev = index
                count = 1
            end
            if (count == _G.K) then
                beginOne = j - (_G.K - 1)
                beginTwo = beginString
                dirColumn = column
                deleted = true
                break
            end
        end
        if (deleted) then
            break
        end
    end
    if (deleted) then
        local buffer = {}
        local endX
        if (dirColumn) then
            endX = beginOne + _G.K - 1
        else
            endX = beginTwo
        end
        for i = 1, endX do
            for j = 1, _G.M do
                if (not dirColumn and j >= beginOne and j <= beginOne + _G.K - 1) then
                    if (i ~= endX) then
                        table.insert(buffer, _G.field[i][j])
                    end
                    if (i == 1) then
                        _G.field[i][j] = math.random(1, 6)
                    end
                    if (i >= 2) then
                        _G.field[i][j] = table.remove(buffer, 1)
                    end
                end
                if (dirColumn and j == beginTwo) then
                    if (i <= endX - _G.K) then
                        table.insert(buffer, _G.field[i][j])
                    end
                    if (i <= _G.K) then
                        _G.field[i][j] = math.random(1, 6)
                    else
                        _G.field[i][j] = table.remove(buffer, 1)
                    end
                end
            end
        end
    else
        return false
    end
    return true
end

return tick